name: 'Create ROBOT diffs on Pull requests'

on:
  pull_request:
    branches: [ master ]

jobs:
  stale:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.26
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    steps:
      
      - name: Run ROBOT diff
        uses: actions/checkout@v2
        run: cd src/ontology &&
                git show master:./cl-edit.owl>tmp.owl &&
                sh run.sh robot diff -labels True -left tmp.owl --right cl-edit.owl -format markdown --output diff.md
                
      - name: comment with diff
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "src/ontology/diff.md"
                    
