name: 'Create ROBOT diffs on Pull requests'

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  classify_pr_unreasoned:
    runs-on: ubuntu-latest
    container: obolibrary/odklite:v1.2.32
    steps:
      - uses: actions/checkout@v2
      # Checks-out main branch under "main" directory
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Diff classification
        run: export ROBOT_JAVA_ARGS=-Xmx6G; robot diff --left master/src/ontology/cl-edit.owl --left-catalog master/src/ontology/catalog-v001.xml --right src/ontology/cl-edit.owl --right-catalog src/ontology/catalog-v001.xml -f markdown -o edit-diff.md
      - name: Upload diff
        uses: actions/upload-artifact@v2
        with:
          name: edit-diff.md
          path: edit-diff.md
          
  classify_pr_reasoned:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.32
    steps:
      - uses: actions/checkout@v2
      # Checks-out main branch under "main" directory
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Build reasoned Ontology
        run: make cl-full.owl
      - name: Diff classification
        run: export ROBOT_JAVA_ARGS=-Xmx6G; robot diff --left master/cl-full.owl --right cl-full.owl -f markdown -o reasoned-diff.md
      - name: Upload diff
        uses: actions/upload-artifact@v2
        with:
          name: reasoned-diff.md
          path: reasoned-diff.md
          
  post_comment:
    needs: [classify_pr_unreasoned, classify_pr_reasoned]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download diff
        uses: actions/download-artifact@v2
        with:
          name: edit-diff.md
          path: edit-diff.md
      - name: Prepare edit comment
        run: "echo \"Here's a diff of your unreasoned edit file: \n\" >edit-comment.md; cat edit-diff.md/edit-diff.md >>edit-comment.md"
      - name: Post edit comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../edit-comment.md"
      - name: Prepare reasoned comment
        run: "echo \"Here's a diff of your reasoned file: \n\" >reasoned-comment.md; cat reasoned-diff.md/reasoned-diff.md >>reasoned-comment.md"
      - name: Post reasoned comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../reasoned-comment.md"
