
   
name: Inference diff

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  classify_pr:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.32
    steps:
      - uses: actions/checkout@v2
      - name: Classify ontology
        run: cd src/ontology; make IMP=FALSE PAT=FALSE cl.owl
      - name: Upload PR cl.owl
        uses: actions/upload-artifact@v2
        with:
          name: cl-PR.owl
          path: src/ontology/cl.owl
          retention-days: 1
  classify_master:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.32
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Classify ontology
        run: cd src/ontology; make make IMP=FALSE PAT=FALSE cl.owl
      - name: Upload master cl.owl
        uses: actions/upload-artifact@v2
        with:
          name: cl-master.owl
          path: cl.owl
          retention-days: 1
  diff_classification:
    needs:
      - classify_pr
      - classify_master
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.32
    steps:
      - uses: actions/checkout@v2
      - name: Download master classification
        uses: actions/download-artifact@v2
        with:
          name: cl-master.owl
          path: cl-master.owl
      - name: Download PR classification
        uses: actions/download-artifact@v2
        with:
          name: cl-pr.owl
          path: cl-pr.owl
      - name: Diff classification
        run: export ROBOT_JAVA_ARGS=-Xmx6G; cd src/ontology; robot diff --left ../../reasoned-master.owl/cl.owl --left-catalog catalog-v001.xml --right ../../reasoned-pr.owl/cl.owl --right-catalog catalog-v001.xml -f markdown -o classification-diff.md
      - name: Upload diff
        uses: actions/upload-artifact@v2
        with:
          name: classification-diff.md
          path: src/ontology/classification-diff.md
  post_comment:
    needs: diff_classification
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Download diff
        uses: actions/download-artifact@v2
        with:
          name: classification-diff.md
          path: classification-diff.md
      - name: Prepare comment
        run: "echo \"Here's a diff of how these changes impact the classified ontology: \n\" >comment.md; cat classification-diff.md/classification-diff.md >>comment.md"
      - name: Post comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../comment.md"