name: 'Manual ROBOT diff on full file'

on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  full_file:
    runs-on: ubuntu-latest
    container: obolibrary/odklite:v1.2.32
    steps:
      - uses: actions/checkout@v2
      # Checks-out main branch under "main" directory
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Diff classification
        run: export ROBOT_JAVA_ARGS=-Xmx6G; robot diff --labels True --left master/cl-full.owl --right src/ontology/cl-full.owl -f markdown -o full-diff.md
      - name: Upload diff
        uses: actions/upload-artifact@v2
        with:
          name: full-diff.md
          path: full-diff.md
  post_comment:
    needs: full_file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download edit diff
        uses: actions/download-artifact@v2
        with:
          name: full-diff.md
          path: full-diff.md
      - name: Prepare edit file comment
        run: "echo \"<details>\n <summary> Here's a diff of your edit file (unreasoned) </summary> \n\" >full-comment.md; cat full-diff.md/full-diff.md >>full-comment.md"
      - name: Post comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../full-comment.md"
          identifier: "full"